language: node_js
node_js:
  - "8"
services:
  - mongodb
before_script:
  - yarn install
script:
<<<<<<< HEAD
  - yarn seed
  - sleep 15

=======
  - node ./dbSeed/seed
  - sleep 15
  - yarn format
  - yarn fix
  - yarn lint
>>>>>>> ddd9e05ab85ae86805e26afaf10f0f5562c2688b

