language: node_js
node_js:
  - "8"
services:
  - mongodb
before_script:
  - yarn install
script:
  - node ./dbSeed/seed
  - sleep 5
  - yarn format
  - yarn fix
  - yarn lint
  - sleep 5
  - yarn test
cache:
  directories:
    - node_modules
